# Dockerfile for ml-anomaly-detection service
FROM python:3.8-slim

RUN pip install scikit-learn pandas psycopg2-binary kafka-python

WORKDIR /app

COPY ./scripts/model.py .

CMD ["python", "model.py"]
